platform :ios, '15.0'
use_frameworks! :linkage => :static

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  pod 'CapgoCapacitorLlm', :path => '../../node_modules/@capgo/capacitor-llm'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
  pod 'CapacitorCommunityInAppReview', :path => '../../node_modules/@capacitor-community/in-app-review'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorCommunitySpeechRecognition', :path => '../../node_modules/@capacitor-community/speech-recognition'
  pod 'CapacitorCommunityTextToSpeech', :path => '../../node_modules/@capacitor-community/text-to-speech'
  pod 'CapacitorFirebaseAuthentication', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'GoogleSignIn', '9.0.0'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      if target.name == 'CapacitorFirebaseAuthentication'
        existing_flags = config.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
        unless existing_flags.include?('RGCFA_INCLUDE_GOOGLE')
          config.build_settings['OTHER_SWIFT_FLAGS'] = "#{existing_flags} -DRGCFA_INCLUDE_GOOGLE"
        end
        existing_paths = config.build_settings['FRAMEWORK_SEARCH_PATHS'] || '$(inherited)'
        unless existing_paths.include?('GoogleSignIn')
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] = "#{existing_paths} \"$(PODS_CONFIGURATION_BUILD_DIR)/GoogleSignIn\""
        end
      end
    end
  end
end
